Update DeploytoSalesforceProduction.yml

diff --git a/.github/workflows/DeploytoSalesforceProduction.yml b/.github/workflows/DeploytoSalesforceProduction.yml
--- a/.github/workflows/DeploytoSalesforceProduction.yml
+++ b/.github/workflows/DeploytoSalesforceProduction.yml
@@ -1,9 +1,9 @@
-name: Deploy to Salesforce Production
+name: Validate changes in Salesforce Production
 on:
   pull_request:
-    types: [opened,reopened]
+    types: [opened, reopened]
     branches:
-      - main
+      - master
 jobs:
   deploy:
     runs-on: ubuntu-latest
@@ -16,18 +16,33 @@ jobs:
         with:
           node-version: "16.x"
 
-      - name: Install Dependencies
-        run: |
-          npm install -g sfdx-cli  
-          npm install salesforce/plugin-login@1.2.8
-      
-      - name: Auth
-        run:
-          npm install -g sfdx-cli  
-          npm install salesforce/plugin-login
-          
-      - uses: sfdx-actions/setup-sfdx@v1
+      - name: Cache SFDX CLI
+        id: cache-sfdx-cli
+        uses: actions/cache@v2
         with:
-          sfdx-auth-url: ${{ secrets.DEVHUB_SFDX_URL }}
-      - name: sfdx-test-run
-        run: sfdx force:apex:test:run -l RunLocalTests -w 30
+          path: ~/.local/share/sfdxcli
+          key: ${{ runner.os }}-sfdx-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-sfdx-
+
+      - name: Install Dependencies
+        if: steps.cache-sfdx-cli.outputs.cache-hit != 'true'
+        run: |
+          npm install -g sfdx-cli@7.120.0 || exit 1
+
+      - name: 'Populate auth file with DEVHUB_SFDX_URL and DEVHUB_SFDX_AUTH_URL secrets'
+        shell: bash
+        run: |
+          echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
+          secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
+          if [ $secretFileSize == 1 ]; then
+            echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
+            exit 1;
+          fi
+
+      - name: Authenticate Dev Hub
+        run: |
+          sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -d -a devhub
+
+      - name: Validate changes
+        run: sfdx force:source:deploy --checkonly --sourcepath force-app --target-org devhub --wait 10
